import {Platform, Dimensions, StyleSheet} from 'react-native';

import {Colors} from '../constants';
import normalize from './normalize';

const letterSpacing = 0.31;
const lineHeight = 20;
export default Texts = StyleSheet.create({
  HEIGHT: Dimensions.get('window').height,
  WIDTH: Dimensions.get('window').width,
  //texts
  heading24TextGreen: {
    fontSize: normalize(24, 'width'),
    color: Colors.mainBgColor,
    // fontWeight: 'bold',
    lineHeight: 32,
    textAlign: 'center',
    fontFamily: 'Lato-Bold',
    width: normalize(320, 'width'),
  },
  heading14Text: {
    fontSize: normalize(14, 'width'),
    color: '#5A5656',
    lineHeight: 21,
    textAlign: 'center',
    fontFamily: 'Lato-Regular',
    width: normalize(320, 'width'),
    fontWeight: '900',
  },
  darkText14: {
    fontSize: normalize(14, 'width'),
    color: Colors.darkText,
    lineHeight: 18,
    textAlign: 'center',
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
  },
  darkText12: {
    fontSize: normalize(12, 'width'),
    color: Colors.darkText,
    // lineHeight: normalize(21, 'width'),
    fontFamily: 'Lato-Regular',
    fontWeight: '300',
  },
  textInputLabel: {
    fontSize: normalize(13, 'width'),
    color: Colors.placeholderTextColor,
    lineHeight: 16,
    // textAlign: 'center',
    fontFamily: 'Lato-Regular',
    alignSelf: 'flex-start',
    fontWeight: '500',
  },
  textInputLabel2: {
    fontSize: normalize(13, 'width'),
    color: Colors.placeholderTextColor,
    lineHeight: 16,
    // textAlign: 'center',
    fontFamily: 'Lato-Regular',
    // alignSelf: 'flex-start',
    fontWeight: '500',
    width: normalize(320, 'width'),
  },
  text14green: {
    fontSize: normalize(14, 'width'),
    color: '#62BF41',
    lineHeight: 18,
    textAlign: 'center',
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
  },
  dummy: {
    flex: 1,
  },
  title23green: {
    fontSize: normalize(23.184, 'width'),
    color: Colors.textColor,
    fontFamily: 'Lato-Regular',
    fontWeight: 'bold',
    // letterSpacing: -1.008,
    // lineHeight: 32,
  },
  text13gray: {
    fontSize: normalize(13.24, 'width'),
    color: Colors.gray,
    // lineHeight: normalize(32, 'width'),
    textAlign: 'center',
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
  },
  title36green: {
    fontSize: normalize(36, 'width'),
    color: Colors.mainBgColor,
    fontFamily: 'Lato-Regular',
    fontWeight: 'bold',
    letterSpacing: -1.824,
    textAlign: 'center',
    // lineHeight: 32,
  },
  darkText14height32: {
    fontSize: normalize(14, 'width'),
    color: Colors.darkText,
    lineHeight: 32,
    textAlign: 'center',
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
  },
  darkText10: {
    fontSize: normalize(10, 'width'),
    lineHeight: 10,
    textAlign: 'center',
    fontFamily: 'Lato-Regular',
  },
  darkText18: {
    fontSize: normalize(18, 'width'),
    lineHeight: 15,
    textAlign: 'center',
    fontFamily: 'Lato-Regular',
    fontWeight: 'bold',
  },
  lightText17: {
    fontSize: normalize(17, 'width'),
    lineHeight: 32,
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
    color: '#62BF41',
  },
  lighttext13gray: {
    fontSize: normalize(12, 'width'),
    color: Colors.gray,
    textAlign: 'center',
    fontFamily: 'Lato-Regular',
    // lineHeight: 17,
    // letterSpacing: 0.57,
  },
  darkText17: {
    fontSize: normalize(17, 'width'),
    lineHeight: 32,
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
    color: Colors.darkText,
  },
  darkText15: {
    fontSize: normalize(15, 'width'),
    lineHeight: 32,
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
    color: Colors.darkText,
  },
  lighttext13green: {
    fontSize: normalize(13, 'width'),
    color: '#4AB945',
    // textAlign: 'center',
    fontFamily: 'Lato-Regular',
    lineHeight: 17,
    fontWeight: '500',
  },
  lighttext14black: {
    fontSize: normalize(14, 'width'),
    color: '#3A291D',
    fontFamily: 'Lato-Regular',
    lineHeight: 17,
    fontWeight: '600',
  },
  lighttext16black: {
    fontSize: normalize(16.27, 'width'),
    color: '#3A291D',
    fontFamily: 'Lato-Regular',
    lineHeight: 19,
    fontWeight: '600',
  },
  lighttext10green: {
    fontSize: normalize(10, 'width'),
    color: Colors.darkText,
    fontFamily: 'Lato-Regular',
    lineHeight: 17,
    fontWeight: '500',
  },
  lighttext11green: {
    fontSize: normalize(11.62, 'width'),
    color: Colors.darkText,
    fontFamily: 'Lato-Regular',
    lineHeight: 19,
    fontWeight: '500',
  },
  darktext20green: {
    fontSize: normalize(20, 'width'),
    color: Colors.darkText,
    fontFamily: 'Lato-Regular',
    lineHeight: 32,
    fontWeight: '500',
  },
  lighttext10brown: {
    fontSize: normalize(10, 'width'),
    color: '#AF7751',
    fontFamily: 'Lato-Regular',
    lineHeight: 17,
    fontWeight: '500',
  },
  lighttext11brown: {
    fontSize: normalize(11.62, 'width'),
    color: '#AF7751',
    fontFamily: 'Lato-Regular',
    lineHeight: 19,
    fontWeight: '500',
  },
  lighttext13greenlineHeight20: {
    fontSize: normalize(13, 'width'),
    color: '#4AB945',
    // textAlign: 'center',
    fontFamily: 'Lato-Regular',
    lineHeight: 20,
    fontWeight: '500',
  },
  lighttext19gray: {
    fontSize: normalize(20, 'width'),
    color: Colors.gray,
    fontFamily: 'Lato-Regular',
    lineHeight: 32,
    fontWeight: '900',
    paddingLeft: 10,
  },
  lightGray13: {
    fontSize: normalize(13, 'width'),
    color: Colors.placeholderTextColor,
    lineHeight: 16,
    // textAlign: 'center',
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
    // paddingLeft: normalize(30, 'width'),
    paddingLeft: 30,
  },
  text11gray: {
    fontSize: normalize(11.04, 'width'),
    color: Colors.gray,
    lineHeight: 15,
    fontFamily: 'Lato-Regular',
    fontWeight: 'normal',
    letterSpacing: -0.48,
  },
  text13lightgray: {
    fontSize: normalize(12.24, 'width'),
    color: Colors.lightGrayText,
    lineHeight: 22,
    fontFamily: 'Lato-Regular',
    fontWeight: 'normal',
    letterSpacing: -0.576,
    marginLeft: 11.4,
  },
  darkText18green: {
    fontSize: normalize(18, 'width'),
    lineHeight: 32,
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
    color: Colors.darkText,
    paddingTop: normalize(15, 'height'),
    paddingLeft: normalize(30, 'width'),
  },

  text11mediumgreen: {
    fontSize: normalize(11.04, 'width'),
    color: Colors.lightGreen,
    lineHeight: 20,
    fontFamily: 'Lato-Regular',
    fontWeight: 'normal',
    letterSpacing: -0.48,
    textAlign: 'center',
  },
  lightGree18: {
    fontSize: normalize(18.5607, 'width'),
    textAlign: 'right',
    fontFamily: 'Lato-Regular',
    fontWeight: '600',
    color: '#62BF41',
  },
  lightRed10: {
    fontSize: normalize(10, 'width'),
    lineHeight: 20,
    textAlign: 'right',
    fontFamily: 'Lato-Regular',
    fontWeight: 'bold',
    color: '#F47458',
  },
  darkGreen10: {
    fontSize: normalize(10.311, 'width'),
    lineHeight: 17,
    textAlign: 'right',
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
    color: Colors.darkText,
  },
  text15gray: {
    fontSize: normalize(15.5182, 'width'),
    color: Colors.gray,
    lineHeight: 32,
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
  },
  text13green: {
    fontSize: normalize(13.24, 'width'),
    color: Colors.mainBgColor,
    lineHeight: 20,
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
  },
  text1324lightgray: {
    fontSize: normalize(13.24, 'width'),
    color: Colors.lightGrayText,
    fontFamily: 'Lato-Regular',
    fontWeight: '900',
  },
  text15darkgreen: {
    fontSize: normalize(15.5182, 'width'),
    color: '#55A334',
    lineHeight: 32,
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
  },
  text23darkgreen: {
    fontSize: normalize(23.184, 'width'),
    color: Colors.darkText,
    lineHeight: 32,
    fontFamily: 'Lato-Regular',
    fontWeight: '900',
    letterSpacing: -1.008,
  },
  settingText: {
    fontSize: normalize(17.664, 'width'),
    color: Colors.gray,
    lineHeight: 32,
    fontFamily: 'Lato-Regular',
    fontWeight: '600',
    paddingLeft: normalize(10, 'width'),
  },
  lightText18: {
    fontSize: normalize(18.9714, 'width'),
    lineHeight: 23,
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
    color: Colors.mainBgColor,
    letterSpacing: -0.82484,
  },
  lightText29: {
    fontSize: normalize(29.6469, 'width'),
    fontFamily: 'Lato-Regular',
    fontWeight: 'bold',
    color: Colors.mainBgColor,
    letterSpacing: -0.82484,
  },
  text11cyan: {
    fontSize: normalize(11.04, 'width'),
    color: '#4B9B89',
    fontFamily: 'Lato-Regular',
    fontWeight: 'normal',
    textAlign: 'center',
  },
  text15grayAE: {
    fontSize: normalize(15.546, 'width'),
    color: '#AEAEAE',
    fontFamily: 'Lato-Regular',
    fontWeight: 'normal',
    lineHeight: 32,
  },
  text15mediumgreen: {
    fontSize: normalize(15.456, 'width'),
    color: Colors.lightGreen,
    fontFamily: 'Lato-Regular',
    fontWeight: 'bold',
    letterSpacing: -0.67,
    textAlign: 'right',
  },
  text15lightgray: {
    fontSize: normalize(15.456, 'width'),
    color: Colors.gray,
    fontFamily: 'Lato-Regular',
    fontWeight: 'normal',
    marginLeft: 11.4,
  },
  text15lightgraywithoutmargin: {
    fontSize: normalize(15.456, 'width'),
    color: Colors.gray,
    fontFamily: 'Lato-Regular',
    fontWeight: 'normal',
    // lineHeight: 32,
  },
  text12placeholderColor: {
    fontSize: normalize(12, 'width'),
    color: Colors.placeholderTextColor,
    textAlign: 'center',
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
    lineHeight: 14,
  },
  bankBarText: {
    fontSize: normalize(17.664, 'width'),
    color: Colors.darkText,
    lineHeight: 32,
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
  },
  bankText: {
    fontSize: normalize(17.664, 'width'),
    color: Colors.gray,
    lineHeight: 32,
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
  },
  text15mediumgray: {
    fontSize: normalize(15.456, 'width'),
    color: Colors.lightGrayText,
    fontFamily: 'Lato-Regular',
    fontWeight: 'normal',
  },
  errorMessageText: {
    fontSize: normalize(13.248, 'width'),
    color: '#F47458',
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
    alignSelf: 'flex-start',
  },
  darkText17Bold: {
    fontSize: normalize(17.69, 'width'),
    color: Colors.darkText,
    fontFamily: 'Lato-Regular',
    fontWeight: '700',
  },
  darkGrayText10: {
    fontSize: normalize(10, 'width'),
    color: Colors.darkGrayText,
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
  },
  LatonormalGrayText15: {
    fontSize: normalize(15, 'width'),
    color: Colors.grayText,
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
  },
  text26greenbold: {
    fontSize: normalize(26, 'width'),
    color: Colors.mainBgColor,
    fontFamily: 'Lato-Regular',

    fontWeight: 'bold',
  },
  text33greenboldheading: {
    fontSize: normalize(33, 'width'),
    color: Colors.mainBgColor,
    fontFamily: 'Lato-Regular',

    fontWeight: 'bold',
    textAlign: 'center',
  },
  yellowText13: {
    fontSize: normalize(13, 'width'),
    color: Colors.yellowText,
    textAlign: 'center',
    fontFamily: 'Lato-Regular',
    fontWeight: '500',
  },
  maingreenText17: {
    fontSize: normalize(17, 'width'),
    lineHeight: 32,
    fontFamily: 'Lato-Regular',
    fontWeight: 'bold',
    color: Colors.mainBgColor,
  },
  text13normalLightgray: {
    fontSize: normalize(13, 'width'),
    color: Colors.lightGrayText,
    fontFamily: 'Lato-Regular',
    fontWeight: 'normal',
  },
});
